### ISSUE TITLE
When the window is maximised on one monitor, notifications appear on monitor to the left

### ISSUE THREAD

**Issue by pingu2k4** [raflop/ToastNotifications#1]
I have a 2 monitor setup, main monitor on left and second monitor on the right.

I positioned the Notifications area at top right, as suggested. When the window is not maximised, the notifications appear correctly. However when the window is maximised, they appear at the top left of my second monitor.

**Comment by raflop** [comment]
The cause of the problem was WPF popup control which was to smart :) 
I changed implementation, and now it should works in your case.
