### ISSUE TITLE
.netcore3 support?

### ISSUE THREAD

**Issue by andyb1979** [raflop/ToastNotifications#100]
Hello :) 

Are you planning to support .NET Core 3? It's a fairly easy conversion in the projects, so long as your dependencies support netcore3 as well. 

Best regards,

**Comment by rafallopatka** [comment]
Yes I think I will do this in some future :)

**Comment by cdesch** [comment]
Anything we can do to help? I'm looking for a .Net Core 3.1 version

**Comment by cdesch** [comment]
@rafallopatka are you planning .NET Core support for a TN v3.0? Do you want to create a branch that we can contribute to for .NET Core Support?
