### ISSUE TITLE
ClearByTag throws NullReferenceException if there is a notification with a null tag

### ISSUE THREAD

**Issue by timothylcooke** [raflop/ToastNotifications#101]
### Library version
2.5.1

### Expected behaviour
ClearAll(new ClearByTag(tag)) should handle null as its own value. If you set the tag to clear to be null, it should clear any notifications with a null tag. If you set the tag to clear to an instance of an object, it should leave any notifications with a null tag.

### Actual behaviour
If there are any notifications with a null tag, a NullReferenceException is thrown when you call ClearAll(new ClearByTag(tag)).

### Steps to reproduce behaviour
See above

### Code to reproduce behaviour
See above

**Comment by timothylcooke** [comment]
Please see my pull request: https://github.com/rafallopatka/ToastNotifications/pull/102

**Comment by rafallopatka** [comment]
Nuget package with provided pull request, will be published soon
