### ISSUE TITLE
Cannot find resource named 'SuccessIcon'. Resource names are case sensitive.

### ISSUE THREAD

**Issue by arminops** [raflop/ToastNotifications#113]
### Library version
2.5.1
### Expected behaviour
Show the toast notification
### Actual behaviour
Show exception with message: Cannot find resource named 'SuccessIcon'. Resource names are case sensitive.

### Steps to reproduce behaviour
Registering servicecollection:
`
            
           Notifier notifier = new Notifier(p =>
            {
                p.PositionProvider = new WindowPositionProvider(
                    parentWindow: Current.MainWindow,
                    corner: Corner.TopRight,
                    offsetX: 10,
                    offsetY: 10);

                p.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
                    notificationLifetime: TimeSpan.FromSeconds(3),
                    maximumNotificationCount: MaximumNotificationCount.FromCount(5));

                p.Dispatcher = Current.Dispatcher;
            });
            serviceCollection.AddSingleton(provider => notifier);`

inject in page and use the show method:

`            
             private readonly Notifier _notifier;
            _notifier.ShowSuccess("Order accepted");`

also i registered the resources in app.xaml
`
<ResourceDictionary x:Key="notification">
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/ToastNotifications.Messages;component/Themes/Default.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
`

**Comment by mspahic** [comment]
Sorry, what was the solution for this?

**Comment by elia-c** [comment]
Same problem, how have you solved?
