### ISSUE TITLE
Keeping Notification Open

### ISSUE THREAD

**Issue by yehiasalam** [raflop/ToastNotifications#17]
Is there any way to keep the notification open till I close it?

**Comment by raflop** [comment]
Hey I made fix for this issue. 

If you set NotificationLifeTime to NotificationSource .NeverEndingNotification notifications will be closed only if user do that, or number of currently visible notifications exceeds MaximumNotificationCount

For example:
            NotificationSource = new NotificationsSource
            {
                MaximumNotificationCount = 5,
                NotificationLifeTime = TimeSpan.FromSeconds(3)
            };

Please checkout newest develop branch and check if it works in your case. After that I will merge it to master, and release nuget.

**Comment by raflop** [comment]
I released this feature in version 1.5.0

**Comment by yehiasalam** [comment]
cool thanks man
