### ISSUE TITLE
Implementation suggestion: consider using FP Option

### ISSUE THREAD

**Issue by BrainCrumbz** [raflop/ToastNotifications#19]
Hi

looking randomly at code, e.g. in `NotificationPopup.cs` [here](https://github.com/raflop/ToastNotifications/blob/15275cfadadb62c3682aa4dee2f3de60442307ee/ToastNotifications/NotificationPopup.cs#L72) there are several cases where a method needs to perform a lot of null checks, and return early if there's a null, or do something if it lands past the last check. 

This type of code, inherently due to the way WPF controls and properties are provided, might be changed using *Option* types (a concept coming from Functional Programming). We recently found out a C# library porting some of those concept over to .NET, https://github.com/louthy/language-ext, and thought you might find it useful as well. BTW, we're in no way associated with that project, nor get any benefits from this.

A code like this:

```c#
private static void IsOpenChanged(DependencyObject dependencyObject,
    DependencyPropertyChangedEventArgs eventArgs)
{
    var popup = dependencyObject as NotificationPopup;
    if (popup == null)
        return;

    if (eventArgs.NewValue == eventArgs.OldValue)
        return;

    bool isOpen = (bool) eventArgs.NewValue;

    if (popup._window == null)
        return;

    if (isOpen)
        popup._window.Show();
    else
        popup._window.Hide();
}
```

might turn into something similar to (not checked against compiler, but just to give an idea of how it could look):

```c#
private static void IsOpenChanged(DependencyObject dependencyObject,
    DependencyPropertyChangedEventArgs eventArgs)
{
    var popupOption = new Option(dependencyObject as NotificationPopup);

    var windowOption =
      from popup in popupOption
      where (eventArgs.NewValue != eventArgs.OldValue)
      from window in popup._window;

    bool isOpen = (bool)eventArgs.NewValue;

    windowOption.Match(
      Some: window => isOpen ? window.Show() : window.Hide(), 
      None: () => { /* do nothing */ });
}
```

The same refactoring could be applied in other cases when there are repeated null-checks, or repeated if-error checks, or (with *Either* type) when there's a right possible result and a wrong one.

**Comment by raflop** [comment]
Hi, this is nice concept and I think it will be useful in production code, but for this library, it might be a little too much, cause i'don't want add dependencies to other libraries. 

In other hand I could implement monada by myself and use it in this library, and maybe I will do that in the future. 

Thanks for your contribution!:)

**Comment by BrainCrumbz** [comment]
You're right on not adding more dependencies if not absolutely necessary. To the purpose of having a few classes (like it might be for *Option<>* or *Either<>* and thei extension methods), I guess you can just have them within your library. Please, try dropping a line if you're looking for some help on this. Thank you!
