### ISSUE TITLE
Specify notification timeout

### ISSUE THREAD

**Issue by Unforgiven-wanda** [raflop/ToastNotifications#2]
I would like to be able to specify the amount of time a toast notification appears for. Change it to 10 seconds for example, or have a toast notification that simply doesn't go away until dismissed by the user. Is that possible?

Thank you

**Comment by raflop** [comment]
> I would like to be able to specify the amount of time a toast notification appears for. Change it to 10 seconds for example

It's possible by setting NotificationSource.NotificationLifeTime in ViewModel. 
I updated readme and example in repo to show how to do that.

**Comment by Unforgiven-wanda** [comment]
Ah yes, I had completely forgotten that I had opened an issue about that. And yes, I did it then exactly like you're suggesting now. Thank you for the readable code, you're a lifesaver.
