### ISSUE TITLE
Cannot change width of the NotificationTray

### ISSUE THREAD

**Issue by selvendiranj** [raflop/ToastNotifications#20]
Please provide an option to change the width of the notification tray. Thanks

**Comment by raflop** [comment]
Hi, sorry for long delay, I would like to add this in version 2, currently code in this version is messy and even so simple change like that you mention will cause other problems. In version 2 I would like to add more control of appearence and behaviours.

**Comment by selvendiranj** [comment]
Thanks for considering. Let me know if you need any help

**Comment by raflop** [comment]
Hi, 

Now its availaible on version 2.1.0, please read the docs at https://github.com/raflop/ToastNotifications

Best regards
