### ISSUE TITLE
Option to change font size

### ISSUE THREAD

**Issue by RavishaHesh** [raflop/ToastNotifications#21]
First of all, Great plugin. Thank You.
Issue: On tablets it's harder to read message on the toast. So can you add a option increase font size?

**Comment by raflop** [comment]
Hi, sorry for long delay, I would like to add this in version 2, currently code in this version is messy and even so simple change like that you mention will cause other problems. In version 2 I would like to add more control of appearence and behaviours.

**Comment by raflop** [comment]
Hi, 

Now its availaible on version 2.1.0 
Please read the docs at https://github.com/raflop/ToastNotifications

Best regards
