### ISSUE TITLE
Is it possible to bind click handlers?

### ISSUE THREAD

**Issue by cb-dtf** [raflop/ToastNotifications#24]
I like the simplicity using this project, but am missing one feature.
I would like to bind event handlers, for example MouseLeftButtonDown when clicking a Notification.

Is this possible today?
(I've had no success so far, I can bind the events, but they never trigger)

**Comment by raflop** [comment]
Hi, sorry for long delay, currently it's not possible, I will add this in v2

**Comment by raflop** [comment]
Hi, 

Now its availaible on version 2.1.0 
Please read the docs at https://github.com/raflop/ToastNotifications

Best regards

**Comment by cb-dtf** [comment]
Niiiiiice.Best regards Christopher BonitzFrom a Android deviceOn Mar 24, 2017 4:51 PM, Rafał <notifications@github.com> wrote:Hi,
Now its availaible on version 2.1.0
Please read the docs at https://github.com/raflop/ToastNotifications
Best regards
