### ISSUE TITLE
Toast notifications appear upside down

### ISSUE THREAD

**Issue by Zelxin** [raflop/ToastNotifications#26]
The notifications appear upside down if you disconnect your session then reconnect.
This is the only way I've found to repeat this issue.
![image](https://cloud.githubusercontent.com/assets/4154793/24773519/94f58e6e-1ae3-11e7-996e-cb31649553b7.png)

**Comment by raflop** [comment]
Weird thing, I will try to reproduce that.

**Comment by Zelxin** [comment]
The steps I used were
1. Start program 
2. Show a few notifications.
3. Use Task Manager to disconnect myself.
4. Reconnect, at this point any notifications in the program would appear upside down.

If you want I can upload a sample application.

**Comment by raflop** [comment]
Hi, 

What you mean by disconnect session, lock user or switch to different one ? 
What system do you have? 

I tried to reproduce that on Windows 10 using your steps (both lock, and switch to different user) and every time it worked fine on my example.

Please upload your example.

**Comment by Zelxin** [comment]
I'm using windows 10 fully patched. This is happening on multiple systems. I originally found out because it was being used over remote desktop.
I'm using the disconnect option from task manager. I don't think it happens when you lock the screen.
![image](https://cloud.githubusercontent.com/assets/4154793/26259294/5eb511d8-3c96-11e7-8389-e69106f8e824.png)

![image](https://cloud.githubusercontent.com/assets/4154793/26260213/633b7afe-3c9a-11e7-803d-412d524ed2f9.png)

![image](https://cloud.githubusercontent.com/assets/4154793/26260231/71a942b0-3c9a-11e7-84ed-9f034a937ee1.png)

[ToastTest.zip](https://github.com/raflop/ToastNotifications/files/1015082/ToastTest.zip)

**Comment by raflop** [comment]
Hi,
I think I resolved that problem, please checkout followin branch and give me feedback if It works for you.
https://github.com/raflop/ToastNotifications/tree/hotfix/%2326_Toast_notifications_appear_upside_down

If everything is fine I will publish new nuget.

**Comment by Zelxin** [comment]
Yes, those changes fixed the issue. Thank you.

**Comment by raflop** [comment]
Hi I published nuget v 2.1.3
