### ISSUE TITLE
Toast popup position changes when mahapps app fullscreen

### ISSUE THREAD

**Issue by sarsw** [raflop/ToastNotifications#27]
I reproduced with the included BasicUsageExample Mahapps example by double clicking the title bar to go full screen and pressing the buttons to launch a popup. The popups appear away from the corner.  I first noticed this with my own Mahapps based application with the notifications in the BottomLeft not appearing on the screen at all when my app goes full screen Mahapps style (no title bar).

Update:I'm operating with 3 screens if that is influencing the coordinates & the Release version will not build in VS2017 : error MSB3322: Unable to get MD5 checksum for the key file "../../Build/DevCrew.ToastNotifications.pfx". Could not find file 'H:\Downloads\ToastNotifications-master-v2\Build\DevCrew.ToastNotifications.pfx'

Update: Resolved the build error by deleting the entries from the project files and testing on a single monitor system still has the coordinate issue when resizing the window.

**Comment by raflop** [comment]
Ok, I will check that

**Comment by raflop** [comment]
Fixed in nuget v 2.1.2.
