### ISSUE TITLE
Close Toast after some task

### ISSUE THREAD

**Issue by MenezesVinicius** [raflop/ToastNotifications#28]
Hello, how can I close a toast after some task? For example, I'm showing a toasting with the info "Adding data to server", after adding the data, I would like to close the Toast. I'm using MVVM in my project. Sorry for posting this here, but I did not find any other place to find info about it. Thanks!

**Comment by raflop** [comment]
:) have you solve that ?

**Comment by MenezesVinicius** [comment]
Well, my workaround: When I start a Task to retrieve data from a server, I create a notifier with CountBasedLifetimeSupervisor(maximumNotificationCount: MaximumNotificationCount.FromCount(0)), then when the data is retrieved, I have to create a new notifier using TimeAndCountBasedLifetimeSupervisor(TimeSpan.FromSeconds(3), MaximumNotificationCount.FromCount(0)), so, as just one toast can be shown at the screen, the previous one is replaced by the new one (TimeBased). But, I still did not find a way to close direcly a notifier using CountBasedLifeTime. I hope you understand and sorry about the English :)

**Comment by MenezesVinicius** [comment]
Well, I just figured out now, is just simply as using: 
```
_notifier?.Dispose();
_notifier = null;
```

**Comment by raflop** [comment]
Ok, you can do that in that way, but I think I will have to add possibility to close specified notifications in some way, but it may take me a while to find a free time :)
