### ISSUE TITLE
ToastNotifications doesn't work with DPI aware applications

### ISSUE THREAD

**Issue by Lakritzator** [raflop/ToastNotifications#33]
With Windows 10, my display is 1920x1080, DPI settings is at 125%

Your IPositionProvider gives for GetHeight 864, and for a popup GetPosition returns 1275,6;-10
(864*1,25 = 1080!!! )

My IPositionProvider gives for GetHeight 1030 (1080-taskbar height, also tried 1080) and for the popup GetPosition returns 1660,-60

With Windows 7 I have the same Display size, and the same values coming from my IPositionProvider, but everything works. (there is no DPI Awareness there)

I am guessing that if I change  my DPI settings from 125% to 100%, logout & in, everything works.
As it's pretty much impossible to unaware my DPI Aware application, I will need to find a fix.
Or I will need to find another solution as ToastNotifcations.

Anyway I just wanted to create this ticket right now, so it's known to other developers.
And than we see how we continue.

**Comment by raflop** [comment]
It looks like pull request created by @ZmorzynskiK fixed that, in my test it works for WPF windows.

Thank you for help, this is released in nuget v2.2.5

**Comment by Lakritzator** [comment]
Hey, that is great news, I will try it out and will only report back if I find that it doesn't work.
Thanks!
