### ISSUE TITLE
Crash when remote connexion to another computer

### ISSUE THREAD

**Issue by FranckZF** [raflop/ToastNotifications#34]
Hi,
first of all, thanks for your work !

i've an issue when i connect to a remote computer, which is already running an application which shows some notifications (a few per seconde for the test).
So application is already running, showing some notification, on a computer (Windows 8) with 2 screens, and when i connect from my windows 8 computer (with the standard window remote connexion), the application crashes, as you can see it here : 
![crash_notification](https://cloud.githubusercontent.com/assets/29091033/26624530/738f5424-45f1-11e7-97c7-50d364eae9d2.png)

if i launch the application when connected to the remote computer, no problem, all is ok, crash happen when the program is already running before i connect to remote computer...

here is how i initialize the notifier : 
            m_notifier = new Notifier(cfg =>
            {
                cfg.PositionProvider = new WindowPositionProvider(
                    parentWindow: Application.Current.MainWindow,
                    corner: Corner.BottomRight,
                    offsetX: 20,
                    offsetY: 40);

                cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
                    notificationLifetime: TimeSpan.FromSeconds(30),
                    maximumNotificationCount: MaximumNotificationCount.FromCount(6));

                cfg.Dispatcher = Application.Current.Dispatcher;
            });

and here how i show the message 👍 
         Application.Current.Dispatcher.BeginInvoke(new Action(() =>
                    {
                        try
                        {
                            switch (a_logMessage.Level)
                            {
                                case EMessageLevel.Error:
                                    m_notifier.ShowError(l_sMessage);
                                    break;
                                case EMessageLevel.Information:
                                    m_notifier.ShowInformation(l_sMessage);
                                    break;
                                case EMessageLevel.Warning:
                                    m_notifier.ShowWarning(l_sMessage);
                                    break;
                                default:
                                    m_notifier.ShowInformation(l_sMessage);
                                    break;
                            }
                        }
                        catch (Exception ex) ...
                        
feel free to ask me some question if needed.

Thanks,

Franck

**Comment by raflop** [comment]
Hi, could you try debug sources to find exact place in library where this exception is fired ? 
It would help me to fix that bug then.

**Comment by raflop** [comment]
closed because of no response
