### ISSUE TITLE
I created updates

### ISSUE THREAD

**Issue by b-mi** [raflop/ToastNotifications#36]
This is nice library.
I modified it:
- support .net framework 4
- add ClearMessages method (all or some message). It allow clear all visible messages, or disable duplicity of notifications - hiding old notification before show new notification with the same message
- add GetMessage() method - getting text
- add CanClose option for single notidication - disable automatic close of it
- add Action option for Notidfication
- add FreezeOnMouseEnter notification option - Notification do not hide if user enter it with mouse
- Notifications are Queued, no one is simple closed. Queued notification are show after another notification are closed / hidden
- fixed problem with MaximumNotificationCount
- add Tag property to MessageOptions
- added GetOptions method
- moved MesageOptions to Core project

Do someone want these updates, can I somewhere post them?

**Comment by raflop** [comment]
Hi,

Thanks for contribution !:) Could you share the code with me via pull request? I would like to see your changes and include it in current branch.

Best regards!

**Comment by b-mi** [comment]
I sent updates by github desktop app. I do not use github, so I'm not sure updates was really sent. If not, please give me know.

**Comment by raflop** [comment]
Hi,

Thanks! I'm checking it, I will let you know what next :) Could you investigate how to create pull requests in github, I think this would be helpfull to merge your changes into my library.

Best regards.

**Comment by raflop** [comment]
This is huge, great job! Definitely it's worth to include your changes into this library.
Please create a pull request, it will be easier to merge it.

**Comment by b-mi** [comment]
Thanks, I created a pull request, I hope correctly.

**Comment by raflop** [comment]
Yes it's correct, I merged your changes, before I release new nugget I will make some additional changes and bug fixes. Thanks a lot!
