### ISSUE TITLE
.NET 4.0 compatibility 

### ISSUE THREAD

**Issue by jordanl010** [raflop/ToastNotifications#37]
Hey there! I love your work on this project. Is there any support for toast notifications V2 for a wpf app running on .net 4.0? I tried downgrading to toast notifications V1 but the position provider to show on top of the parent window is the functionality I'm primary looking for. I have a wpf app that runs in the background and hidden and 4.5 can run this with the pop ups top right of the windows screen and V1, I can only show them in the window of the wpf app.

**Comment by raflop** [comment]
Hi, 

I think it's possible to downgrade library to .NET 4.0 and compile it with c# 6
This is related with #36, I will look into this issue with help of @b-mi.

Best regards

**Comment by b-mi** [comment]
Current version is compatible with .net framework 4.0

**Comment by raflop** [comment]
Hi,

I released new nuget 2.2.0 which contains requested changes, thanks to @b-mi for great help

Best Regards
