### ISSUE TITLE
Crashed the mouse enter to notification

### ISSUE THREAD

**Issue by dualbios** [raflop/ToastNotifications#47]
The application crashed when the notification does not contain Border control as top level control  and user move mouse to notification.
Relation: NotificationDisplayPart.OnMouseEnter.

**Comment by b-mi** [comment]
NotificationDisplayPart.OnMouseEnter was fixed in last version - do you use last version?

**Comment by dualbios** [comment]
as i see your pull request with fix does not merged into master.

**Comment by b-mi** [comment]
I think it have to merge raflop. (I'm not sure, I fight with git a lot, I usually use TFS)
But my yesterday pull request was about something else.
If you can, try ToastNotification from https://github.com/b-mi/ToastNotifications, if it solve that problem. If not, need more information how to invoke problem.

**Comment by raflop** [comment]
Now all changes from b-mi are merged into the master. It will be released in nuget v2.2.2
