### ISSUE TITLE
NotificationsWindow should ignore window shortcuts

### ISSUE THREAD

**Issue by pfattisc** [raflop/ToastNotifications#50]
When you focus a notification and then enter typical window shortcuts like _Windows Button + Arrow Key_  (move window on screen) or _ALT + Spacebar_ (open window's contextmenu) the NotificationsWindow obeys the input and moves on the screen(s) while the main application window remains at its original position.
![bug_notificationswindow](https://user-images.githubusercontent.com/11867529/29605618-d4f42f1e-87eb-11e7-9b67-c57eb6443e71.gif)

**Comment by raflop** [comment]
this fix will be released in version 2.2.2
