### ISSUE TITLE
Is it supported for windows Vista and 7

### ISSUE THREAD

**Issue by redkozubov** [raflop/ToastNotifications#51]
Sorry, didn't find information about support for older versions of windows

**Comment by b-mi** [comment]
I tested it on Windows 7 and Windows XP (and of course Windows 10), so I think it have to work on Windows Vista too.

**Comment by raflop** [comment]
Hi, 

As b-mi already said it works on windows 7 for sure, vista worked also when I started this project, only requirement is a .NET 4

Best regards
