### ISSUE TITLE
Problem with PrimaryScreenPositionProvider

### ISSUE THREAD

**Issue by Chapre** [raflop/ToastNotifications#54]
Hi;

This library is amazing it does just what I want.
I've encountered a issue: when I use PrimaryScreenPositionProvider in a Notifier; my main apllication never exit. It's seem like all notification wincreated are still alive even if they fade away.

Can you please help

**Comment by raflop** [comment]
Hi,

You have to dispose notifier instance when it's no longer needed - in Your case when app is closing

notifier.Dispose();

Best regards

**Comment by Chapre** [comment]
Hi raflop;
I'm definitely disposing the notifier whence closing the when the app is close, but no luck.

I've also tried the example provided on the repository "ConfigurationExample"; when any other PositionProvider is selected, the app closes successfully when the main window is close but with PrimaryScreenPositionProvider although the mainwidows UI closes, the app is still running in the background.

**Comment by Exxili** [comment]
I too get this same issue,  However in my Window Closing event I am using notifier.Dispose(),  The code does call this function, however it does not appear to do anything and I am left with a hidden application running in Windows Task manager with the same name as my application.

**Comment by raflop** [comment]
Hi.
Now its fixed in 2.2.3 - nuget is published,

Best regards
