### ISSUE TITLE
Notification Stay on screen until User confirmation

### ISSUE THREAD

**Issue by MartIssues** [raflop/ToastNotifications#59]
Hi there,  

Is there a way to create a notification that will stay on the screen using PrimaryScreenPositionProvider, with a Confirmation button "Ok".  

this notification will not close and will be "sticky" E.g if other notifications pop up while this notification is open it will still remain on screen.

the only way to close this Notificaiton is to press the "ok" button?

**Comment by jconnop** [comment]
@MartIssues you can kind of get this if you specify an arbitrarily large notification lifetime. The notifications will then stay put effectively forever until dismissed (via either the X button or a click handler calling .Close() ).

i.e. 
`cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
                           notificationLifetime:TimeSpan.FromDays(365),
                           maximumNotificationCount:MaximumNotificationCount.FromCount(15)
)`

I think to get an OK button you'd have to use a [custom defined notification type](https://github.com/raflop/ToastNotifications/blob/master-v2/Docs/CustomNotificatios.md).
