### ISSUE TITLE
How can i change the size of my custom notification?

### ISSUE THREAD

**Issue by alero3** [raflop/ToastNotifications#61]
### Questions
I tried to set a different Height and Width in CustomDisplayPart.xaml but my notification window is cut, such that width is the same as the "standard" notification. I want my custom notification to be bigger.
![notification_screen](https://user-images.githubusercontent.com/15707118/33989686-a79b5e62-e0c8-11e7-9d4c-4210a0791de6.jpg)

**Comment by kTime** [comment]
@alero3 you need to change the DisplayOptions.Width value when creating the Notifier instance
i.e. .... new Notifier(tn =>
{
  ...
 tn.DisplayOptions.Width = <Width of the notification panel you desire>
 ...
}

**Comment by chodi150** [comment]
And how about the height?

**Comment by rafallopatka** [comment]
Custom notification height depends only on your notification DisplayPart (layout) . You can make it fixed size or adapt to its content.

Example:

<core:NotificationDisplayPart x:Class="CustomNotificationsExample.CustomMessage.CustomDisplayPart"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:CustomNotificationsExample.CustomMessage"
             xmlns:core="clr-namespace:ToastNotifications.Core;assembly=ToastNotifications"
             mc:Ignorable="d"  Background="Gray"
             d:DesignHeight="60" d:DesignWidth="250"

                             **MinHeight="500"**

             d:DataContext="{d:DesignInstance local:CustomNotification, IsDesignTimeCreatable=False}" >
    <Grid  Margin="5">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <TextBlock Text="{Binding Title}" FontWeight="Bold" Foreground="White" />
        <TextBlock Text="{Binding MessageText}" FontWeight="Light" Foreground="White" Grid.Row="1" TextWrapping="Wrap" />

    </Grid>
</core:NotificationDisplayPart>
