### ISSUE TITLE
keyboard input is not possible.

### ISSUE THREAD

**Issue by eventjang** [raflop/ToastNotifications#65]
Good morning.
We are creating a hybrid app using HTML.
I need the Notification function in my app, so I am developing it as Custom Notification provided by the library.

I added CEFSharp's WebView in Custom Notification.xaml, and it loads an HTML page.
There is a text input in the HTML page, but keyboard input is not possible.
I want to know what the cause is. Is there a way to fix it?

**Comment by raflop** [comment]
The thing is that the default behaviour of notifier is to block all input events which may interrupt notifications. Now it's possible to override this behaviour.
