### ISSUE TITLE
Crash outside Visual Studio

### ISSUE THREAD

**Issue by MasterPK** [raflop/ToastNotifications#66]
Hi,
I add simple notifications to my program and if i run it in Visual Studio it works fine. But if i run same exe file that runs VS from file explorer and run notifications, app crashes without error messege or some exception. I download sample project and it works fine, so i copy samle in my project but it crashes anyway. I would appreciate any help.
Thank you.
Petr

EDIT: Okay, i figure out that if i use PrimaryScreenPositionProvider it is okay, but if i use WindowPositionProvider it crashes.

**Comment by raflop** [comment]
Hey, it is weird :) 

Could you add some logging code to file in the sample app, and check what the exception was? 

You can do that by adding a try catch block around notifier.show method and log the exception to the file.

**Comment by stu094** [comment]
Hi,
I cant seem to find if this issue has been fixed. 
I still receive a NullReferenceException at the ToastNotifications.Position.WindowPositionProvider constructor when using my app outside of Visual Studio. Using PrimaryScreenPositionProvider works fine.
Thank you,
Stu
