### ISSUE TITLE
Clarification: does it support notifications outside main window?

### ISSUE THREAD

**Issue by BrainCrumbz** [raflop/ToastNotifications#7]
Hello

me and my team are looking for a toaster notification library in WPF and came through your library. Thanks for sharing it.

One question though: does it support showing notification in main screen/desktop, so outside of main application window? Potentially also when application is running but main window is minimized, ot application runs from the "system tray"?

Something along the lines of [this other library](https://github.com/zachatrocity/netoaster) we found, where you can set _position_ to be _PrimaryScreenXxxYyy_ or _ApplicationXxxYyy_.

Thanks

**Comment by raflop** [comment]
Hi currently it's not possible, maybe in the future, but i need to find some free time to do that, or someone else do that and share via pull request ;)

**Comment by BrainCrumbz** [comment]
There are some (minor) PRs already. You might want to have a look at those. If you start accepting one, we can rebase the others consequently, although there should not be conflicts. Tnx

**Comment by jking257** [comment]
` public NotificationPopupWindow(FrameworkElement attachedElemnt)
        {
            InitializeComponent();
  
            this.Activate(); // insert this line and rebuild project; Copy new ToastNotification.dll and Add references to your project
            SetProperties(attachedElemnt);

            Loaded += OnLoaded;
            Unloaded += OnUnloaded;
 }`

**Comment by raflop** [comment]
will be done in version 2

**Comment by raflop** [comment]
Hi, version 2 is now available and mentioned feature also. You can use different position  providers to move   notifications to different locations on a screen. In your case use PrimaryScreenPositionProvider, more about that  you can find in the docs and samples. If this is not enough you can create your own PositionProvider by implementing a IPositionProvider interface.

**Comment by BrainCrumbz** [comment]
Thanks for keeping us posted! Will try it in a future update of our application. Cheers!

**Comment by BrainCrumbz** [comment]
BTW maybe there's a typo in readme examples, where it says:

```c#
// PrimaryScreenPositionProvider
Notifier notifier = new Notifier(cfg =>
{
    cfg.LifetimeSupervisor = new TimeAndCountBasedLifetimeSupervisor(
        notificationLifetime: TimeSpan.FromSeconds(3),
        maximumNotificationCount: MaximumNotificationCount.FromCount(5));
    /* * */
});
```

Comment probably should say *TimeAndCountBasedLifetimeSupervisor*

**Comment by raflop** [comment]
You're right, now its fixed.
Thanks!
