### ISSUE TITLE
How to set notifications to be at the same position as the application?

### ISSUE THREAD

**Issue by adrilolo9** [raflop/ToastNotifications#76]
Hello, I was wondering how can I set the notifications at the same position that the application currently is, what I mean by saying that is that in case of some app goes on top of my main application the notification hides behind that new app, you'll clearly see what I mean in the next pictures. Thanks.
![configurationexample_2018-10-01_14-02-31](https://user-images.githubusercontent.com/28511609/46287452-d5e86e00-c582-11e8-8195-96db6c27bbed.png)
![explorer_2018-10-01_14-03-20](https://user-images.githubusercontent.com/28511609/46287463-dc76e580-c582-11e8-9898-5512f27cc070.png)

**Comment by rafallopatka** [comment]
Hi,

This is because topmost option is enabled by default. You can disable it like this:
```csharp         
new Notifier(cfg =>
            {
                cfg.PositionProvider = CreatePositionProvider(corner, relation);
                cfg.LifetimeSupervisor = CreateLifetimeSupervisor(lifetime);
                cfg.Dispatcher = Dispatcher.CurrentDispatcher;
                cfg.DisplayOptions.TopMost = false;
            });
```

Best regards

**Comment by adrilolo9** [comment]
Thank you very much :)
