### ISSUE TITLE
Crash when manual close a message.

### ISSUE THREAD

**Issue by pgbo** [raflop/ToastNotifications#77]
Version: 2.5.0

### Steps to reproduce behaviour
1. Use ControlPositionProvider as position provider, configure a page view as position tracker.
2. Show some notifications.
3. Exit the page, the page view is not active now, the notifications are still visible.
4. Manual close  a notification, application crash.

Below is the exception trace.

System.InvalidOperationException: 此 Visual 未连接到 PresentationSource。
   在 System.Windows.Media.Visual.PointToScreen(Point point)
   在 ToastNotifications.Position.ControlPositionProvider.GetPosition(Double actualPopupWidth, Double actualPopupHeight)
   在 ToastNotifications.Display.NotificationsDisplaySupervisor.UpdateWindowPosition()
   在 ToastNotifications.Display.NotificationsDisplaySupervisor.<>c__DisplayClass10_0.<Close>b__0()
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Is there a method to solve this problem?

**Comment by rafallopatka** [comment]
Hi,

Do you call dispose on notifier before page exits? 
When you use ControlPositionProvider you tie instance of notifier with this control, so when this control removed you have to also dispose notifier and create another one if you need, it depends on your usecase.

Best regards
