### ISSUE TITLE
Use toast Notifications with Header, Subheader and message

### ISSUE THREAD

**Issue by figueiredorj** [raflop/ToastNotifications#82]

**Comment by figueiredorj** [comment]
Hi,
could someons guide on how to use this library to customize a toast with a header and subheader and toast message?

thanks

**Comment by rafallopatka** [comment]
Hi,

You can simply create a custom notification, you can follow instructions  from this
https://github.com/rafallopatka/ToastNotifications/blob/master-v2/Docs/CustomNotificatios.md


W dniu 19 lis 2018, o 13:17, użytkownik Ricardo Figueiredo <notifications@github.com<mailto:notifications@github.com>> napisał:

Hi,
could someons guide on how to use this library to customize a toast with a header and subheader and toast message?

thanks

**Comment by figueiredorj** [comment]
Thanks,
somehow I missed instructions on how to use it.... which are quite clear I think... :)

Great library, by the way! :)

cheers
