### ISSUE TITLE
Trouble asks, mouse moves on toast, toast won't disappear automatically, how to handle

### ISSUE THREAD

**Issue by chdown** [raflop/ToastNotifications#84]
2.5.0.0

Trouble asks, mouse moves on toast, toast won't disappear automatically, how to handle

**Comment by rafallopatka** [comment]
There is an configuration option called FreezeOnMouseEnter 
https://github.com/rafallopatka/ToastNotifications/blob/master-v2/Docs/Configuration.md#message-options
