### ISSUE TITLE
Using ToastNotifications in a Class Library

### ISSUE THREAD

**Issue by nik-net** [raflop/ToastNotifications#85]
### Library version
Latest NuGet package as of today
### Expected behaviour
ToastsNotification Will show up when Notifier is used with ShowErrorMessage
### Actual behaviour
System.Windows.Markup.XamlParseException- Exception: Cannot find resource named 'ErrorIcon'. Resource names are case sensitive.
### Steps to reproduce behaviour
1. Create a WPF Class Library project without App.XAML
2. Add a Window (WPF) user control to it
3. Add ToastsNotification NugetPackage
4. Use MergeDictionary in Windows.Resources section of XAML
5. WIthin the Window control use Notifier class to show message
6. Add a caller Application to reference this class library and use the window control
### Code to reproduce behaviour
Attached.
### Questions
[ToastNotificationProblem.zip](https://github.com/rafallopatka/ToastNotifications/files/2770359/ToastNotificationProblem.zip)

**Comment by DubaiVirus** [comment]
try adding this to your App.xaml

<ResourceDictionary Source="pack://application:,,,/ToastNotifications.Messages;component/Themes/Default.xaml" />

**Comment by DubaiVirus** [comment]
<ResourceDictionary Source="pack://application:,,,/ToastNotifications.Messages;component/Themes/Default.xaml" />

**Comment by ghost** [comment]
try adding this to your App.xaml:

![image](https://user-images.githubusercontent.com/46894763/51478880-f84e0380-1d8c-11e9-9e45-1da29325f9a9.png)

the code i pasted here wasn't showing up so i had to take a screen shot

**Comment by rafallopatka** [comment]
Actually solution above is quite good, Styles for this library must be included explicitely in application scope styles - App.xaml in final application. You can try to add this programatically to simplify this process, but current approach is a standard way.

**Comment by dontboyle** [comment]
@rafallopatka Not trying to revive anything, however are there any updates on how to use this outside of App.xaml? or is that "that". - thanks
