### ISSUE TITLE
NullReferenceException on non wpf app

### ISSUE THREAD

**Issue by b00ted** [raflop/ToastNotifications#88]
### Library version
2.5.1
### Expected behaviour
Show notification
### Actual behaviour
Null reference exception
### Steps to reproduce behaviour
Create **winforms** app
Add WPF window with Notifier
Try to show notification
### Questions
The problem is in `CreateConfiguration()` method in Notifier.cs.
In this case there is no `Application.Current` at all, so `Dispatcher = Application.Current.Dispatcher` throws an exception.
So simplest way to solve this - just adding  **?** after `Application.Current`

**Comment by jonnyb023** [comment]
In your WinForms app, just call this in your Program.Main for C#
`var app = new System.Windows.Application();`

Or this in your ApplicationEvents MyApplication.MyApplication_Startup for VB
`Dim app As New System.Windows.Application`

**Comment by rafallopatka** [comment]
Is @jonnyb023 's answer fixed your problem?
