### ISSUE TITLE
Different life time for notifications

### ISSUE THREAD

**Issue by uday-teja** [raflop/ToastNotifications#92]
Hi would like to give different life time for notifications. can anyone help me achieve this ?

**Comment by rafallopatka** [comment]
Hi,

Check that https://github.com/rafallopatka/ToastNotifications/blob/master-v2/Docs/Configuration.md#notification-lifetime

You can change between different lifetimes, customize them, or create your own implementation.

Best regards.

**Comment by uday-teja** [comment]
Here, i would like to create a single instance of notifier and later i want to change only lifetime for it.

**Comment by rafallopatka** [comment]
It's not supported as it is shown in examples, when you want to switch lifetime and other crucial settings, you have to dispose existing notifier and create new one with new configuration

**Comment by uday-teja** [comment]
Okay Thank you 👍 but, its nice to have this feature.
