### ISSUE TITLE
Urgent Help Requested : Parent window is getting activated and coming in to focus 

### ISSUE THREAD

**Issue by cvanama** [raflop/ToastNotifications#93]
Hi Friends, 

When ever i the toaster is displayed on the window, that window is activating and coming into focus, even i am not on that window. 

My WPF app can open multiple windows for different purpose, on certain action or event will trigger to display a toaster notification on the window X. I am working something on Window Y. 
But when the toaster shows my window X is coming into Focus which is disturbing my work on Y.

My requirement is toaster notification should come and go on its way and should not activate the parent window if i am not in focus at that time.

Please help me as quick as possible.

**Comment by rafallopatka** [comment]
Try configuring notifier like this

new Notifier(cfg =>
            {
           /***/
                cfg.DisplayOptions.TopMost = false;
            });
