### ISSUE TITLE
Exception on custom mesage

### ISSUE THREAD

**Issue by fredericoregateiro** [raflop/ToastNotifications#94]
### Library version
2.5.0
### Expected behaviour
No exceptions raised, on the samples and on the documentation there is no mention to the 
`Bind(customNotification);`

### Actual behaviour
Exception is throw on mouse enter the notification

### Steps to reproduce behaviour
Run the MahAppsNotification sample and hover the mouse on the notification

### Code to reproduce behaviour
The MahAppsNotification sample

![error](https://user-images.githubusercontent.com/6304701/61248209-87d7dc00-a74a-11e9-90dd-b3f7c78c936b.png)

**Comment by rafallopatka** [comment]
Hi,

Thank you for spotting this error, I fixed it.

Best regards
